"""empty message

Revision ID: 8f661403e039
Revises: 3859081d406c
Create Date: 2024-02-26 22:33:38.034881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f661403e039'
down_revision = '3859081d406c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'resolved', 'rejected', name='status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'resolved', 'rejected', name='status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
