"""empty message

Revision ID: a3a0733712b1
Revises: 25116099f31b
Create Date: 2024-02-26 22:40:42.992945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a0733712b1'
down_revision = '25116099f31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'resolved', 'rejected', name='status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'resolved', 'rejected', name='status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
